apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  route:
    receiver: "default"
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: "default"
        matchers:
          - name: severity
            value: critical
  receivers:
    - name: "default"
