apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  route:
    receiver: "default"
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: "default"
        matchers:
          - name: severity
            value: critical
  receivers:
    - name: "default"
