apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-prometheus-rule
  namespace: monitoring
spec:
  groups:
    - name: example
      rules:
        - alert: HighRequestLatency
          expr: http_request_duration_seconds_sum / http_request_duration_seconds_count > 0.5
          for: 5m
          labels:
            severity: page
          annotations:
            summary: "High request latency"
