apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-alerts
  namespace: monitoring
  labels:
    app: prometheus
spec:
  groups:
    - name: kubernetes
      rules:
        - alert: PodNotRunning
          expr: kube_pod_container_status_running{namespace=~"development|production"} == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Pod has been in a non-running state for more than 5 minutes
            description: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in a non-running state for more than 5 minutes.
