apiVersion: v1
kind: Pod
metadata:
  name: test-pod-invalid
  namespace: default
spec:
  containers:
    - name: test-container
      image: nginx
      command: ["/bin/sh", "-c", "exit 1"] # Force the container to exit with error
