package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
)


type whoami struct {
	FirstName  string
	LastName   string
}

func main() {
	request1()
}

func whoAmI(response http.ResponseWriter, r *http.Request) {
	who := []whoami{
		whoami{FirstName: "Pierre",
			LastName: "Bonnet",
		},
		whoami{FirstName: "Arthur",
			LastName: "Buisson",
		},
		whoami{FirstName: "Timothee",
			LastName: "Fougeron",
		},
	}

	json.NewEncoder(response).Encode(who)

	fmt.Println("Endpoint Hit", who)
}

func homePage(response http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(response, "Welcome to the Web API!")
	fmt.Println("Endpoint Hit: homePage")
}

func generateError(response http.ResponseWriter, r *http.Request) {
	errorMsg := "ERROR: This is a test error generated by the /generate-error endpoint"
	log.Println(errorMsg)
	http.Error(response, errorMsg, http.StatusInternalServerError)
}

func aboutMe(response http.ResponseWriter, r *http.Request) {
	who := "EfreiParis"

	fmt.Fprintf(response, "A little bit about me...")
	fmt.Println("Endpoint Hit: ", who)
}

func request1() {
	http.HandleFunc("/", homePage)
	http.HandleFunc("/aboutme", aboutMe)
	http.HandleFunc("/whoami", whoAmI)
	http.HandleFunc("/generate-error", generateError)

	log.Fatal(http.ListenAndServe(":8080", nil))
}
