apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
  namespace: monitoring
spec:
  containers:
    - name: cpu-stress
      image: polinux/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      args:
        - -cpus
        - "1"
        - -timeout
        - "15m"
